### ISSUE TITLE
Fix Linting Errors

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#270]
### Issue description
> **ESTIMATE** TBD

At the end of this task, `npm run lint` should pass perfectly fine. Most of the issues should be fixable automatically, but there are still a few hundred that will need to be reviewed.
 
As of the writing of the ticket, here is the count of linting issues:
* `npm run lint:src`
   :heavy_multiplication_x: 13202 problems (13202 errors, 0 warnings)
   13004 errors and 0 warnings potentially fixable with the `--fix` option.
* `npm run lint:cypress`
   :heavy_multiplication_x: 300 problems (300 errors, 0 warnings)
   281 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by adriancofie** [comment]
Remaining errors:


4:29  error  (54) 'children' is missing in props validation  

1:27  error  (31) 'Children' is defined but never used               no-unused-vars

78:11  error  (28) 'errorMessage' is assigned a value but never used                                                                                                     no-unused-vars

6:3  error  (20) Jest tests should not return a value           jest/no-test-return-statement

242:3   error (11)  Using this.refs is deprecated   

341:43  error  (8) `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`  react/no-unescaped-entities

1:1  error  (7) Do not export from a test file                      jest/no-export

7:1  error  (6) All hooks must be wrapped in a describe block  jest/require-top-level-describe

19:6  error (5) Static HTML elements with event handlers require a role  

89:9   error  (5) `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities                                       jsx-a11y/no-static-element-interactions

35:4   error (4) Non-interactive elements should not be assigned mouse or keyboard event listeners               jsx-a11y/no-noninteractive-element-interactions

14:20  error  (4) Empty block statement  no-empty

19:6  error (3) Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events

302:19  error  (2). It doesn’t work with function components and is deprecated in StrictMode. See https://reactjs.org/docs/react-dom.html#finddomnode  react/no-find-dom-node

20:4  error  (2) Unexpected lexical declaration in case block  no-case-declarations

95:1   error (2)  All test cases must be wrapped in a describe block  jest/require-top-level-describe

302:19  error (2) Do not use findDOMNode. It doesn’t work with function components and is deprecated in StrictMode. See https://reactjs.org/docs/react-dom.html#finddomnode  react/no-find-dom-node

88:4  error  (1) The attribute aria-expanded is not supported by the role heading. This role is implicit on the element h2  jsx-a11y/role-supports-aria-props (1)

208:58  error  (1) Do not pass children as props. Instead, nest children between the opening and closing tags                                                                 react/no-children-prop                                                                                                                         react/no-string-refs

120:5   error (1)  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange
