### ISSUE TITLE
Update print options to use regular checkbox

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#480]
As part of removing Redux, the print options for the checkboxes on the Trial Results page should use the regular checkbox implementation.

**Comment by adriancofie** [comment]
The CTS Results Page (code below) currently makes usage of the custom checkbox component located `/clinical-trials-search-app/src/components/atomic/Checkbox/Checkbox.jsx`  This component, in turn, uses Redux --**solely for analytics tracking.** . The component currently abstracts this analytics logic, and this alone.  

This ticket is intended to replace the Checkbox component on the Results Page and elsewhere in the code base with a standard checkbox.

In order to complete this ticket, a non-redux solution for handling the input change tracking `dispatch(trackFormInputChange(inputActionProps));` must be implemented within ResultsPage.jsx  / wherever the existing component is being replaced by a standard checkbox. 

Note: Currently in ResultsPage.jsx we are making use of use of `useTracking()` from the 'react-tracking' library.


-----
`src/views/ResultsPage/ResultsPage.jsx`

```

			<Checkbox
				id={cbxId}
				name="select-all"
				label="Select all on page"
				checked={selectAll}
				classes="check-all"
				onChange={handleSelectAll}
			/>
	
```




Existing component:
```
		<div className={`cts-checkbox ${classes}`}>
			<input
				id={id}
				className="cts-checkbox__input"
				type="checkbox"
				name={name}
				onInput={handleInput}
				value={value ? value : id}
				disabled={disabled || false}
				{...otherProps}
			/>
			<label className="cts-checkbox__label" htmlFor={id}>
				{hideLabel ? <span className="show-for-sr">{label}</span> : label}
			</label>
		</div>
	);
```

Analytics action currently dispatched from the Checkbox component:
`/clinical-trials-search-app/src/components/atomic/Checkbox/Checkbox.jsx` 

```

`	const trackInteraction = (event) => {
		const { target } = event;
		const { form, id, value } = target;
		const formName = form && form.id ? form.id : null;
		const inputActionProps = {
			formName,
			id,
			value,
		};
		dispatch(trackFormInputChange(inputActionProps));
	};
```
