### ISSUE TITLE
Modify delighter URLs not to point to specific generated sprite

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#513]
Digital platform CSS is being updated to use dart-sass and it was found that the delighters in CTS are hardcoded to point to an svg sprite in Published Content (https://cancer.gov/PublishedContent/images/images/design-elements/sprites/svg-sprite.__v15577802.svg).  

As a developer, make it so that the delighter images travel with the app and are not hardcoded to point to a fingerprinted sprite on cgov images folder.

> **ESTIMATE** TBD

### Tasks
- [ ] Update CTS app to inline a sprite so that CTS always has the delighter images. (Images will go with the app if ever used elsewhere)
- [ ] Update tarball and inline sprite so that released CTS can use sprites for delighters (not requiring a release of CTS to patch for dart-sass update

**Comment by alinai** [comment]
@alerosad, verified that each delighter icon is individually encoded for whatever is needed, rather than the whole sheet being encoded using the online decoder. Verified the Basic Search page, Advanced Search page, Search Results page, Trial Description page, No Trial Found page, Invalid Search Criteria page. Thanks @alerosad for providing the test step for this.

@sarinapadilla , Noticed that when we hover on the <p> tag under the delighter we used to get underline in Prod. We are not seeing the underline on hovering the <p> tag under the delighter on https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-518/. @alerosad is checking this.
